---
- name: Install Metricbeat
  hosts: webservers
  become: true
  tasks:
  # use command module to download metricbeat deb
  - name: Download Metricbeat .deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  # use command moudle to install metricbeat
  - name: Install Metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  # Use copy module to copy metricbeat-config.yml to metricbeat.yml
  - name: Drop in metricbeat config
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml


  # Use command module to enable metricbeat docker module
  - name: Enable and configure metricbeat docker module
    command: metricbeat modules enable docker


  # Use command module to setup metricbeat
  - name: Setup Metricbeat
    command: metricbeat setup -e

  # Use command module to start metricbeat
  - name: Start metricbeat
    command: service metricbeat start

  # Use systemd module to start metricbeat on boot
  - name: Start metricbeat service on boot
    systemd:
      name: metricbeat
      enabled: yes
